CREATE TABLE PLAYER_RATING (
    VOID_ID INT PRIMARY KEY AUTO_INCREMENT,
    DISCORD_USER_ID INT,
    APEX_ID VARCHAR(128) NOT NULL,
    LATEST_USERNAME VARCHAR(256) NOT NULL,
    PLAYER_RATING DECIMAL(10, 5),
    PLAYER_RATING_VOLATILITY DECIMAL(10, 5)
);
